name: code-style

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  pint:
    runs-on: ubuntu-latest

    name: Laravel Pint

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none
          tools: composer:v2

      - name: Cache composer dependencies
        uses: actions/cache@v5
        with:
          path: ~/.composer/cache/files
          key: composer-pint-${{ runner.os }}-${{ hashFiles('composer.json') }}
          restore-keys: composer-pint-${{ runner.os }}-

      - name: Install dependencies
        run: composer update --prefer-dist --prefer-stable --no-interaction --no-progress

      - name: Run Pint (check only)
        run: vendor/bin/pint --test
